### PR TITLE
Add pyproject.toml and drop setup.py

### PR DESCRIPTION
**Pull request by terop**
This is one step towards adding pycaruna to PyPI.

### CODE REVIEW

**Comment by Jalle19** [comment]
I had for some reason unwatched this repository so I didn't get notified about your PRs. Happened to stumble upon them when I today wanted to debug why the authentication doesn't work anymore!

**Comment by Jalle19** [comment]
Is it necessary to move the files to `src/`?

**Comment by Jalle19** [comment]
Seems like something like this should be added instead of moving to `src/`:

```
packages = [
    { include = "pycaruna" }
]
```

**Comment by Jalle19** [comment]
Maybe it's fine like this, I'm not familiar with pyproject.toml to be honest. Please rebase so we can get this in.

**Comment by terop** [comment]
Actually moving the directory seems not to be needed. When I originally did this I got some odd error but now when I tried this again it worked fine.

**Comment by Jalle19** [comment]
Is the README instructions on how to include this library still working? Or will it need adapting now?

```
git+https://github.com/Jalle19/pycaruna.git@51d3ee12429d68592640cb146ead71541bf14944#egg=pycaruna==1.0.0
```

**Comment by terop** [comment]
An update is needed, I modified `README.md` to use the new working syntax.

**Review by Jalle19 — APPROVED** [review]

**Comment by Jalle19** [comment]
Thanks!

**Comment by terop** [comment]
I think that pycaruna would now be ready for publishing on PyPI. Some documentation on doing this is available at https://packaging.python.org/en/latest/tutorials/packaging-projects.
@Jalle19 could you try PyPI publishing when you have time?

**Comment by Jalle19** [comment]
Yeah, I'll have a look

**Comment by Jalle19** [comment]
https://pypi.org/project/pycaruna/ should be published now. Haven't tried using the released build yet, let's hope it works!

**Comment by terop** [comment]
Thanks!
I tried using the package from PyPI and it works okay for me.

**Comment by Jalle19** [comment]
Great!

**Pull request merged**
